name: HW2 C

on:
  push:
    paths:
      - 'linux'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: download
      run: wget https://github.com/juwonk1018/linux/archive/$(git rev-parse HEAD:linux).zip
    - name: unzip
      run: unzip $(git rev-parse HEAD:linux).zip
    - name: check
      run: ls -al
    - name: build-linux
      run: ./build-linux.sh linux-$(git rev-parse HEAD:linux) tinyconfig

