
name: HW2 C-2

on:
  push:
    paths:
      - 'test/**'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: C-2
      run: make -C test
